version: 2.1

executors:
  default-execution-environment:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/build_directory
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

jobs:
  "Build Source":
    executor: default-execution-environment

    steps:
      # Show some of the CircleCI runtime env variables
      - run:
          name: "Show Runtime Environment Variables"
          command: |-
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
          when: always

      - run:
          name: "Show System Information"
          command: |-
            echo "uname:" $(uname -a)
            echo "arch: " $(arch)
          when: always

      # Checkout the source code
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Download Dependencies for Offline Use"
          command: mvn -Drepo.username=$REPO_USERNAME -Drepo.password=$REPO_PASSWORD -s .circleci/maven-settings.xml dependency:go-offline
          when: always

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Build project and persist results to workspace
      - run:
          name: "Build Source"
          command: mvn -Drepo.username=$REPO_USERNAME -Drepo.password=$REPO_PASSWORD -s .circleci/maven-settings.xml --batch-mode clean install
          when: always

      - persist_to_workspace:
          root: ~/
          paths: build_directory

  "Release Source":
    executor: default-execution-environment
    steps:
      - attach_workspace:
          at: ~/

      - add_ssh_keys
      - run:
          # See issue : https://discuss.circleci.com/t/known-hosts-in-circle-2-0/18544
          name: "Keyscan Github (HACK)"
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - run:
          name: "Configure Git User"
          command: git config --local user.name "tech-rebel" && git config --local user.email "tech.rebel@marabele.africa"
          when: always

      - run:
          name: "Execute Release"
          command: mvn -Drepo.username=$REPO_USERNAME -Drepo.password=$REPO_PASSWORD -s .circleci/maven-settings.xml --batch-mode release:clean release:prepare release:perform
          when: always

workflows:
  version: 2

  "Check-In Build":
    jobs:
      - "Build Source":
          context: REPO_CONTEXT
      - "Approve Source Release":
          type: approval
          requires:
            - "Build Source"
          filters:
            branches:
              only:
                - development
                - hotfix
      - "Release Source":
          requires:
            - "Approve Source Release"
          context: REPO_CONTEXT

  "Nightly Build":
    triggers:
      - schedule:
          cron: "59 23 * * *"
          filters:
            branches:
              only:
                - development
    jobs:
      - "Build Source"


